name: publish
on:
  push:
    tags:
      - 'v*'
jobs:
  dev:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn install
      - name: typecheck
        run: yarn typecheck
      - name: lint
        run: yarn lint:ci
      - name: format
        run: yarn format:ci
      - name: build
        run: yarn main build
      - name: can i publish
        run: yarn can-npm-publish
        working-directory: ./packages/main
      - name: release
        run: npm publish
        working-directory: ./packages/main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
