on:
  push:
    branches:
      - 'main'
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm packages
        run: yarn install
      - name: typecheck
        run: yarn typecheck
      - name: lint
        run: yarn lint:ci
      - name: format
        run: yarn format:ci
      - name: build
        run: yarn main build
      - name: App Deploy
        run: yarn example build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/example/dist
      - name: can i publish
        run: yarn can-npm-publish
        working-directory: ./packages/main
